#!/usr/bin/env node
/**
 * Capture the share image from the built home page, so it can never drift
 * from the words and buttons the page actually shows.
 *
 *     npm run build && node tools/share-image.mjs
 *
 * Serves dist/ locally, opens the home page at 1200x630 in Chrome with reduced
 * motion (the forest's scenes are seeded, so that is one still, repeatable
 * frame), and writes the PNG, with its provenance embedded, to public/og.png
 * and dist/og.png.
 */
import { createServer } from 'node:http';
import { readFile, writeFile } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { crc32 } from 'node:zlib';
import { chromium } from 'playwright';

const root = new URL('..', import.meta.url).pathname;
const dist = join(root, 'dist');
const WIDTH = 1200;
const HEIGHT = 630;
const PROVENANCE =
  `Origin: screenshot of the ecosystem.maison home page hero at ${WIDTH}x${HEIGHT} (headless Chromium via Playwright, tools/share-image.mjs), ` +
  "rendered by this site's own hand-authored pixel-art canvas engine (src/scripts/forest). Not generated by an image model.\n";

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css',
  '.js': 'text/javascript',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.woff2': 'font/woff2',
  '.woff': 'font/woff',
  '.json': 'application/json',
};

/** Just enough of a static server for the home page and its assets. */
function serve() {
  const server = createServer(async (req, res) => {
    let path = normalize(decodeURIComponent(new URL(req.url, 'http://x').pathname));
    if (path.endsWith('/')) path += 'index.html';
    try {
      const body = await readFile(join(dist, path));
      res.writeHead(200, { 'content-type': TYPES[extname(path)] ?? 'application/octet-stream' });
      res.end(body);
    } catch {
      res.writeHead(404).end();
    }
  });
  return new Promise((resolve) => server.listen(0, '127.0.0.1', () => resolve(server)));
}

/** Insert a tEXt chunk straight after IHDR, the same key the shipping rasters use. */
function withProvenance(png) {
  const data = Buffer.from(`impeccable:prompt\0${PROVENANCE}`, 'latin1');
  const type = Buffer.from('tEXt');
  const chunk = Buffer.alloc(12 + data.length);
  chunk.writeUInt32BE(data.length, 0);
  type.copy(chunk, 4);
  data.copy(chunk, 8);
  chunk.writeUInt32BE(crc32(Buffer.concat([type, data])) >>> 0, 8 + data.length);
  const ihdrEnd = 8 + 12 + png.readUInt32BE(8);
  return Buffer.concat([png.subarray(0, ihdrEnd), chunk, png.subarray(ihdrEnd)]);
}

async function launch() {
  // The system Chrome saves a browser download; fall back to Playwright's own.
  try {
    return await chromium.launch({ channel: 'chrome' });
  } catch {
    return await chromium.launch();
  }
}

const server = await serve();
const browser = await launch();
try {
  const page = await browser.newPage({
    viewport: { width: WIDTH, height: HEIGHT },
    deviceScaleFactor: 1,
    reducedMotion: 'reduce',
  });
  await page.goto(`http://127.0.0.1:${server.address().port}/`, { waitUntil: 'networkidle' });
  await page.evaluate(() => document.fonts.ready);
  // Page furniture that means nothing in a link preview: the stop index and its readout.
  await page.addStyleTag({ content: '.index, .whereabouts { display: none !important; }' });
  // Let the forest paint its first frame.
  await page.waitForTimeout(800);
  const png = withProvenance(await page.screenshot({ type: 'png' }));
  await writeFile(join(root, 'public/og.png'), png);
  await writeFile(join(dist, 'og.png'), png);
  console.log(`Wrote public/og.png and dist/og.png (${WIDTH}x${HEIGHT}, ${(png.length / 1024).toFixed(0)} KB)`);
} finally {
  await browser.close();
  server.close();
}
